app/routes.py
from flask import Blueprint, render_template, request, redirect, session
from flask import url_for, flash
from urllib.parse import urlparse, urljoin
from flask_login import LoginManager, login_user, current_user
from flask_login import logout_user
from app import forms
from app.models import db, User, Ticket, Hotel, Customer
from app.models import LogTrail, FlightInquiry, HotelInquiry
from app.models import Package, FlightBooking, StripeCustomer
from app.models import Payments, HotelBooking, PackageBooking
from flask_bcrypt import Bcrypt
from functools import wraps
from datetime import timedelta, date, datetime
import stripe


view = Blueprint('main', __name__, template_folder='templates',
                 static_folder='static', static_url_path='/%s' % __name__)

bcrypt = Bcrypt()

loginManager = LoginManager()
loginManager.login_view = 'main.LogIn'
loginManager.login_message = 'Please log in'
loginManager.login_message_category = 'warning'

pubkey = 'pk_test_GjK3GmJJ1exs60wIcgTpfggq'
secretkey = 'sk_test_RXyvP1FBgkRyCwyEBGyZeymo'

stripe.api_key = secretkey

referenceNumber = datetime.now().strftime("%Y%m%d%H%M%S")


@loginManager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


def login_required(role="ANY"):
    def wrapper(fn):
        @wraps(fn)
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated:
                return loginManager.unauthorized()
            userRole = current_user.role
            if role == "AD":
                if((userRole != role) and role != "ANY"):
                    return loginManager.unauthorized()
            return fn(*args, **kwargs)
        return decorated_view
    return wrapper


# User Side
def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return (test_url.scheme in ('http', 'https') and
            ref_url.netloc == test_url.netloc)


@view.route('/login', methods=['GET', 'POST'])
def LogIn():
    session['next'] = request.args.get('next')
    form = forms.LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user:
            inputPassword = form.password.data
            dbPassword = user.password
            checkBcrypt = bcrypt.check_password_hash(dbPassword, inputPassword)
            role = user.role
            if checkBcrypt:
                login_user(user)
                loggedUser = current_user
                fullName = loggedUser.firstName + ' ' + loggedUser.lastName
                if loggedUser.role == "AD":
                    role = "Admin"
                elif loggedUser.role == "RO":
                    role = "Reservation Officer"
                else:
                    role = "Financial Officer"
                event = (fullName + ' (' + role + ') logged in')
                newLogTrail = LogTrail(event=event)
                db.session.add(newLogTrail)
                db.session.commit()
                if role == "RO":
                    return redirect(url_for('main.UserHomeRO'))
                elif role == "FO":
                    return redirect(url_for('main.UserHomeFO'))
                else:
                    return redirect(url_for('main.UserHomeRO'))
            flash('Invalid Credentials', 'error')
            return render_template('employee/login.html', form=form)
        flash('Username does not Exist', category='error')
        return render_template('employee/login.html', form=form)
    return render_template('employee/login.html', form=form)


@view.route('/user/register', methods=['GET', 'POST'])
def Register():
    form = forms.RegisterForm()
    if form.validate_on_submit():
        passwordBcrypt = bcrypt.generate_password_hash(form.password.data)
        emailUnique = User.query.filter(User.email == form.email.data).all()
        usernameUnique = (User.query
                          .filter(User.username == form.username.data).all())
        if usernameUnique:
            flash('Username already Existing', 'error')
        elif emailUnique:
            flash('Email already Existing', 'error')
        else:
            newUser = User(username=form.username.data,
                           password=passwordBcrypt.decode('utf-8'),
                           firstName=form.firstName.data,
                           lastName=form.lastName.data,
                           email=form.email.data,
                           role=form.role.data)
            db.session.add(newUser)
            if form.role.data == "AD":
                role = "Admin"
            elif form.role.data == "RO":
                role = "Reservation Officer"
            else:
                role = "Financial Officer"
            event = (form.username.data +
                     ' registered as ' +
                     role)
            newLogTrail = LogTrail(event=event)
            db.session.add(newLogTrail)
            db.session.commit()
            return redirect(url_for('main.LogIn'))
    return render_template('employee/register.html', form=form)


@view.route('/logout')
def LogOut():
    user = current_user
    fullName = user.firstName + ' ' + user.lastName
    if user.role == "AD":
        role = "Admin"
    elif user.role == "RO":
        role = "Reservation Officer"
    else:
        role = "Financial Officer"
    event = (fullName + ' (' + role + ') logged out')
    newLogTrail = LogTrail(event=event)
    db.session.add(newLogTrail)
    db.session.commit()
    logout_user()
    return redirect(url_for('main.LogIn'))


# Reservation Officer Side
@view.route('/user/home', methods=['GET', 'POST'])
@login_required(role="RO")
def UserHomeRO():
    return render_template('result.html')


@view.route('/user/home/FO', methods=['GET', 'POST'])
@login_required(role="FO")
def UserHomeFO():
    return render_template('result.html')


@view.route('/ticket/add', methods=['GET', 'POST'])
@login_required(role="RO")
def CreateTicket():
    form = forms.RegisterTicket()
    if form.validate_on_submit():
        expireDate = form.departureDate.data - timedelta(days=7)
        if form.arrivalDate.data < form.departureDate.data:
            errorMessage = ('%s must be greater than %s'
                            % (form.arrivalDate.label.text,
                               form.departureDate.label.text))
            form.arrivalDate.errors.append(errorMessage)
            return render_template('employee/flights/addTicket.html',
                                   form=form)
        if form.returnDate.data < form.arrivalDate.data:
            errorMessage = ('%s must be greater than %s'
                            % (form.returnDate.label.text,
                               form.arrivalDate.label.text))
            form.returnDate.errors.append(errorMessage)
            return render_template('employee/flights/addTicket.html',
                                   form=form)
        newTicket = Ticket(origin=form.origin.data,
                           arrival=form.arrival.data,
                           flightNo=form.flightNo.data,
                           departureDate=form.departureDate.data,
                           departureTime=form.departureTime.data,
                           arrivalDate=form.arrivalDate.data,
                           arrivalTime=form.arrivalTime.data,
                           returnDate=form.returnDate.data,
                           returnTime=form.returnTime.data,
                           expirationDate=expireDate,
                           remainingSlots=form.slots.data,
                           isPackaged=form.isPackaged.data,
                           price=form.price.data)
        db.session.add(newTicket)
        user = current_user
        fullName = user.firstName + ' ' + user.lastName
        if user.role == "AD":
            role = "Admin"
        elif user.role == "RO":
            role = "Reservation Officer"
        else:
            role = "Financial Officer"
        event = (fullName +
                 ' (' + role + ') created ' +
                 form.flightNo.data +
                 ' (' +
                 form.origin.data +
                 '-' +
                 form.arrival.data +
                 ')')
        newLogTrail = LogTrail(event=event)
        db.session.add(newLogTrail)
        db.session.commit()
        return redirect(url_for('main.UserHomeRO'))
    return render_template('employee/flights/addTicket.html', form=form)


@view.route('/hotel/add', methods=['GET', 'POST'])
@login_required(role="RO")
def CreateHotel():
    form = forms.RegisterHotel()
    if form.validate_on_submit():
        if form.checkOut.data < form.checkIn.data:
            errorMessage = ('%s must be greater than %s'
                            % (form.checkOut.label.text,
                               form.checkOut.label.text))
            form.checkOut.errors.append(errorMessage)
            return render_template('employee/hotels/addHotel.html',
                                   form=form)
        if form.checkIn.data <= form.expirationDate.data:
            errorMessage = ('%s must be less than %s'
                            % (form.expirationDate.label.text,
                               form.checkIn.label.text))
            form.expirationDate.errors.append(errorMessage)
            return render_template('employee/hotels/addHotel.html',
                                   form=form)
        newHotel = Hotel(name=form.name.data,
                         roomType=form.roomType.data,
                         capacity=form.capacity.data,
                         details=form.details.data,

app/templates/partials/navbars/_navbarCustomer.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a href="{{ url_for('main.HomePage') }}" class="navbar-brand">
        <img class="img-fluid photoLogo" src="https://preview.ibb.co/ksH4rd/oie_transparent.png" alt="oie_transparent" border="0">
    </a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMenu">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{{ url_for('main.ViewPackages') }}" class="nav-link">Packages</a>
            </li>
            <li class="navbar-item">
                <a href="{{ url_for('main.ViewFlights') }}" class="nav-link">Flights</a>
            </li>
            <li class="navbar-item">
                <a href="{{ url_for('main.ViewHotels') }}" class="nav-link">Hotels</a>
            </li>
            <li class="navbar-item">
                <a href="{{ url_for('main.Inquire') }}" class="nav-link">Inquiry</a>
            </li>
        </ul>
        {% if current_user.is_authenticated  %}
            <ul class="navbar-nav ml-auto">
                <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">
                    {{ current_user.firstName }} {{ current_user.lastName }}
                </a>
                <li class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a href="{% if current_user.is_authenticated  %}
                            {% if current_user.role == 'RO' or 'AD' %}
                                {{ url_for('main.UserHomeRO') }}
                            {% else %}
                                {{ url_for('main.UserHomeFO') }}
                            {% endif %}
                            {% else %}
                                {{ url_for('main.LogIn') }}
                            {% endif %}" class="dropdown-item">Employee Page</a>
                    <a href="{{ url_for('main.LogOut') }}" class="dropdown-item">Log Out</a>
                </li>
            </ul>

        {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{{ url_for('main.LogIn') }}" class="nav-link">Employee Login</a>
                </li>
            </ul>
        {% endif %}
        
    </div>
</nav>

app/templates/partials/navbars/_navbarEmployee.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a href="
    {% if current_user.is_authenticated  %}
        {% if current_user.role == 'RO' or 'AD' %}
            {{ url_for('main.UserHomeRO') }}
        {% else %}
            {{ url_for('main.Register') }}
        {% endif %}
    {% else %}
        {{ url_for('main.LogIn') }}
    {% endif %}
    " class="navbar-brand">
    <img class="img-fluid photoLogo" src="https://preview.ibb.co/ksH4rd/oie_transparent.png" alt="oie_transparent" border="0">
    </a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMenu">
        {% if current_user.is_authenticated  %}
        <ul class="navbar-nav">
            {% if current_user.role != 'FO' %}
            <li class="nav-item">
                <a href="{{ url_for('main.CreatePackage') }}" class="nav-link">Packages</a>
            </li>
            <li class="navbar-item">
                <a href="{{ url_for('main.CreateTicket') }}" class="nav-link">Flights</a>
            </li>
            <li class="navbar-item">
                <a href="{{ url_for('main.CreateHotel') }}" class="nav-link">Hotels</a>
            </li>
            <li class="navbar-item">
                <a href="{{url_for('main.InquiriesLog')}}" class="nav-link">Inquiries</a>
            </li>
            {% endif %}
            {% if current_user.role == 'FO' or current_user.role == 'AD' %}
            <li class="navbar-item">
                <a href="{{ url_for('main.PaymentLogs')}}" class="nav-link">Payment Logs</a>
            </li>
            {% endif %}
            {% if current_user.role == 'AD'  %}
            <li class="navbar-item">
                <a href="{{ url_for('main.LogTrails')}}" class="nav-link">Log Trails</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
        {% if current_user.is_authenticated  %}
            <ul class="navbar-nav ml-auto">
                <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">
                    {{ current_user.firstName }} {{ current_user.lastName }}
                </a>
                <li class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a href="{{ url_for('main.LogOut') }}" class="dropdown-item">Log Out</a>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{{ url_for('main.HomePage') }}" class="nav-link">Customer Screen</a>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>